In [1]:
!pip install numpy

In [2]:
!pip install sklearn

  Running setup.py bdist_wheel for sklearn: started
  Running setup.py bdist_wheel for sklearn: finished with status 'done'
  Stored in directory: C:\Users\Big data\AppData\Local\pip\Cache\wheels\76\03\bb\589d421d27431bcd2c6da284d5f2286c8e3b2ea3cf1594c074
Successfully built sklearn


In [29]:
import numpy as np
from sklearn.linear_model import LinearRegression
npd=np.genfromtxt('0050.csv',delimiter=',')
print(type(npd))
print(npd.ndim,npd.shape,npd.dtype)
print("幾維陣列: " + str(npd.ndim))#幾維陣列
print("幾個元素: " + str(npd.shape))#幾個元素
print("資料型別: " + str(npd.dtype))#資料型別

print(len(npd[1]))
print(npd[1:2])


<class 'numpy.ndarray'>
2 (1287, 72) float64
幾維陣列: 2
幾個元素: (1287, 72)
資料型別: float64
72
[[5.0000000e+01 2.0130102e+07 4.6570000e+01 4.7130000e+01 4.6490000e+01
  4.6920000e+01 1.6487000e+04 6.4000000e-01 3.5000000e-01           nan
            nan           nan           nan           nan           nan
            nan           nan           nan           nan           nan
            nan           nan           nan           nan           nan
            nan           nan           nan           nan           nan
            nan           nan           nan           nan           nan
            nan           nan           nan           nan           nan
            nan           nan           nan           nan           nan
            nan           nan           nan           nan           nan
            nan           nan           nan           nan           nan
            nan           nan           nan           nan 4.6865000e+01
            nan           nan           nan      

In [30]:
# 自己產生x1 & x2 try 多元回歸
import numpy as np
from sklearn.linear_model import LinearRegression

tem=np.array([29,28,34,31,25,29,32,31,24,33,25,31,26,30])
tem_1=np.array([[29,28,34,31,25,29,32,31,24,33,25,31,26,30],[29,28,34,31,25,29,32,31,24,33,25,31,26,30]])
teasales=np.array([77,62,93,84,59,64,80,75,58,91,51,73,65,84])
print(tem)
print(teasales)

#轉換維度
tem=np.reshapee(tem,(len(tm),1))#1*12->12*1 第一個放要轉的array，第二個為要轉成什麼
teasales=np.reshape(teasales,(len(teasales),1))

#tem_1=np.reshape(tem_1,(len(tem_1[1]),2),order="C")#1*12->12*1 第一個放要轉的array，第二個為要轉成什麼
tem_1=tem_1.T


#print(tem_1)
# print(teasales)

lm=LinearRegression()
lm.fit(tem_1,teasales)

#模型績效
mse=np.mean((lm.predict(tem_1)-teasales)**2)
R_squared=lm.score(tem_1,teasales)

print(mse)
print(R_squared)


[29 28 34 31 25 29 32 31 24 33 25 31 26 30]
[77 62 93 84 59 64 80 75 58 91 51 73 65 84]


AttributeError: module 'numpy' has no attribute 'reshapee'

In [34]:
import numpy as np
from sklearn.linear_model import LinearRegression

npd=np.genfromtxt('0050_new.csv',delimiter=',')
npd = np.delete(npd, 0, 0).T #刪除第0列再轉置

npd_x_init=np.array([npd[2]]).T#挑某幾列當我的x 還要再轉回來
x_add = np.array(npd[3])
npd_x_final = np.c_[npd_x_init,x_add.T]
print(npd_x_final)

npd_y=np.array([npd[72]]).T #找y 為了丟進model裡面

print("幾維陣列: " + str(npd_x.ndim))#幾維陣列
print("幾個元素: " + str(npd_x.shape))#幾個元素
print("資料型別: " + str(npd_x.dtype))#資料型別
#print(npd_x)


lm=LinearRegression()
lm.fit(npd_x,npd_y)

#模型績效(MSE & R^2)
mse=np.mean((lm.predict(npd_x)-npd_y)**2)
R_squared=lm.score(npd_x,npd_y)

print(mse)
print(R_squared)

[[53.23 54.29]
 [54.07 54.29]
 [54.2  54.25]
 ...
 [82.9  82.9 ]
 [82.25 82.35]
 [82.65 83.05]]
幾維陣列: 2
幾個元素: (912, 1)
資料型別: float64
0.5116676534457757
0.9938201821563829


In [85]:
def create_x(filename):
    npd=np.genfromtxt(filename,delimiter=',')
    npd = np.delete(npd, 0, 0).T #刪除第0列再轉置
    npd_x_final=np.array(npd[0]).T#挑某幾列當我的x 還要再轉回來
    List_01=create01List(filename)
    for index in range(0,len(List_01)):
        if List_01[index]==1:
            x_add = np.array(npd[index])
            npd_x_final = np.c_[npd_x_final,x_add.T]
    npd_x_final = np.delete(npd_x_final.T, 0, 0).T #把一開始隨便加的刪掉再轉回來
    #print(npd_x_final)

    return(npd_x_final)

[[53.23       54.07       38.41059603 ... 54.19354839 87.93921336
  54.16      ]
 [53.94       54.16       38.41059603 ... 60.         86.28271227
  53.85      ]
 [53.67       53.85       65.16853933 ... 40.         83.01867658
  54.11      ]
 ...
 [82.2        82.25       53.06122449 ... 19.40298507 72.27967287
  82.1       ]
 [81.8        82.1        48.         ... 14.92537313 67.6130062
  82.85      ]
 [82.65       82.85       36.58536585 ... 37.31343284 65.07967287
  82.95      ]]


In [77]:
a=create_x("0050_new.csv")
print(a)

[[5.0000000e+01 2.0140428e+07]
 [5.0000000e+01 2.0140429e+07]
 [5.0000000e+01 2.0140430e+07]
 ...
 [5.0000000e+01 2.0180328e+07]
 [5.0000000e+01 2.0180329e+07]
 [5.0000000e+01 2.0180330e+07]]
[[50.   54.29]
 [50.   54.29]
 [50.   54.25]
 ...
 [50.   82.9 ]
 [50.   82.35]
 [50.   83.05]]
[[  50. 8482.]
 [  50. 6518.]
 [  50. 5598.]
 ...
 [  50. 4161.]
 [  50. 4099.]
 [  50. 4994.]]
[[50.         38.41059603]
 [50.         38.41059603]
 [50.         65.16853933]
 ...
 [50.         53.06122449]
 [50.         48.        ]
 [50.         36.58536585]]
[[50.         53.79310345]
 [50.         52.31316726]
 [50.         47.88273616]
 ...
 [50.         34.67741935]
 [50.         24.32432432]
 [50.         37.16814159]]
[[50.         56.71641791]
 [50.         56.60074826]
 [50.         55.49102429]
 ...
 [50.         53.97078353]
 [50.         53.58470526]
 [50.         55.62051555]]
[[50.         54.15583333]
 [50.         54.17083333]
 [50.         54.1675    ]
 ...
 [50.         83.53333333]

In [73]:
import random
def create01List(filename):
    list_random = [ random.random() for i in range(len(np.genfromtxt(filename,delimiter=',')[1]))]
    for index in range(0,len(list_random)):
        if list_random[index]<=0.5:
            list_random[index]=0
        else:
            list_random[index]=1
    return(list_random)

In [56]:
#print(len(len(np.genfromtxt("0050_new.csv",delimiter=',')))
print(create01List("0050_new.csv"))

[1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0]


In [57]:
print((len(np.genfromtxt("0050_new.csv",delimiter=',')[1])))

73


In [111]:

from itertools import combinations, permutations
npd=np.genfromtxt('0050_new.csv',delimiter=',')
range(0,len(npd[1])+1)
#permutations([1, 2, 3], 2)
list(combinations([1, 2, 3], 2))

[(1, 2), (1, 3), (2, 3)]

In [116]:
#產生c73取2的所有組合
tmp=[]
for index in range(0,len(npd[1])):
    tmp.append(index)
print(tmp)
combination_x=list(combinations(tmp, 2))
    

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]


In [119]:
#產生c73取2的所有組合

C_get=3 #要取幾個?
filename='0050_new.csv'
npd=np.genfromtxt(filename,delimiter=',')
tmp=[]
for index in range(0,len(npd[1])):
    tmp.append(index)
print(tmp)
combination_x=list(combinations(tmp, C_get))
len(combination_x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]


62196

[1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0]
